# -------------------- Finger 1
finger_1_joint_1_position_controller:
  type: effort_controllers/JointPositionController
  joint: finger_1_joint_1
  pid: { p: 100.0, i: 0.01, d: 0.01 }
# finger_1_joint_2_position_controller:
#   type: effort_controllers/JointPositionController
#   joint: finger_1_joint_2
#   pid: { p: 100.0, i: 0.01, d: 0.01 }
# finger_1_joint_3_position_controller:
#   type: effort_controllers/JointPositionController
#   joint: finger_1_joint_3
#   pid: { p: 100.0, i: 0.01, d: 0.01 }
palm_finger_1_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: palm_finger_1_joint
  pid: { p: 100.0, i: 0.01, d: 0.01 }
#-------------------- Finger 2
finger_2_joint_1_position_controller:
  type: effort_controllers/JointPositionController
  joint: finger_2_joint_1
  pid: { p: 100.0, i: 0.01, d: 0.01 }
# finger_2_joint_2_position_controller:
#   type: effort_controllers/JointPositionController
#   joint: finger_2_joint_2
#   pid: { p: 100.0, i: 0.01, d: 0.01 }
# finger_2_joint_3_position_controller:
#   type: effort_controllers/JointPositionController
#   joint: finger_2_joint_3
#   pid: { p: 100.0, i: 0.01, d: 0.01 }
palm_finger_2_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: palm_finger_2_joint
  pid: { p: 100.0, i: 0.01, d: 0.01 }
# -------------------- Middle
finger_middle_joint_1_position_controller:
  type: effort_controllers/JointPositionController
  joint: finger_middle_joint_1
  pid: { p: 100.0, i: 0.01, d: 0.01 }
# finger_middle_joint_2_position_controller:
#   type: effort_controllers/JointPositionController
#   joint: finger_middle_joint_2
#   pid: { p: 100.0, i: 0.01, d: 0.01 }
# finger_middle_joint_3_position_controller:
#   type: effort_controllers/JointPositionController
#   joint: finger_middle_joint_3
#   pid: { p: 100.0, i: 0.01, d: 0.01 }
